config/routes.rb
Rails.application.routes.draw do
  resources :inventories
  resources :checkins
  resources :pronouns
  resources :volunteers
  resources :requests
  resources :events
  resources :churches
  resources :carriers
  resources :messages
  resources :users, only: [:index] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
    post :import, on: :collection
  end
  #resources :offerings
  root to: 'pages#home'

  devise_for :users
  match '/alert',:to => 'checkins#alert', :via => :get
  match '/checkin',:to => 'checkins#checkin', :via => :get
  match '/list',:to => 'checkins#list', :via => :get
  match 'nametag/', :to => 'pages#nametag', :via => :get
  match 'nametags/', :to => 'pages#nametags', :via => :get
  match 'all_users/', :to => 'pages#all_users', :via => :get
  match 'get_user/', :to => 'pages#single_user', :via => :get
  match 'offering/', :to => 'pages#offering', :via => :get
  match 'charge/', :to => 'pages#charge', :via => :post
  match 'test/',:to => 'pages#test', :via => :get
  match '/adminify',:to => 'pages#adminify', :via => :get
  match '/financify',:to => 'pages#financify', :via => :get
  match '/card', :to => 'pages#offeringcard', :via => :get
  match '/sucard', :to => 'pages#sucard', :via => :get
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match '/offerings',:to => 'offerings#index', :via => :get
  match '/missing',:to => 'pages#missing', :via => :get
  match '/stopped',:to => 'pages#stopped', :via => :get
  match '/mediareminder', :to => 'pages#MediaReleaseEmail', :via => :get
  match '/checkinEmail',:to => 'pages#checkinEmail', :via => :get
  match '/PrayerChainEmail',:to => 'pages#PrayerChainEmail', :via => :get
  match '/thankyou',:to => 'pages#thankyouEmail', :via => :get
  match '/ackgift',:to => 'offerings#ack', :via => :get
  match '/parishioners',:to => 'pages#parishioners', :via => :get
  match 'edit',:to => 'users#edit', :via => :get
  match 'edit',:to => 'users#update', :via => :put
  match '/mediarelease', :to => 'pages#mediarelease', :via => :get
  
  mount ActionCable.server => '/cable'
  #resources :sessions, only: [:create,:destroy]
  post ':controller(/:action(/:id(.:format)))'
  get ':controller(/:action(/:id(.:format)))'
  


end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @church = Church.first
    @messages = Message.all
    @users = User.all.where(:sms_ok => true).where.not(telephone: [nil,""],carrier_id: [nil])
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @church = Church.first
  end

  # GET /messages/new
  def new
    @scope = User.all.where(:sms_ok => true).count
    @church = Church.first
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @church = Church.first.name #get name of church
    @subject = "#{@church}-Alert" #set subject
    @count = User.all.where(:sms_ok => true).where.not(telephone: [nil,""],carrier_id: [nil]).count
    @message.count = @count

    UserMailer.email_blast(@subject,@message.body).deliver #deliver message
 
    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_url, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body,:count)
    end
end

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :body, label: "Message" %>
  </div>

  <div class="mt-4 mb-4 mb-12">
    <%= f.button :submit, :class => 'text-2xl' %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div class="container">
<h1 class="m-2 text-xl">Previously Sent Messages</h1>

<table class="table table-striped table-dark table-responsive table-bordered">
  <thead>
    <tr>
      <th>Message</th>
      <th>Time Sent</th>
      <th>Users Reached</th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.body %></td>
        <td><%= message.created_at.to_formatted_s(:long) %></td>
        <td><%= message.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @users.count > 0 %>
<div class="mb-12">
  <span class="px-2 py-1 text-blue-800 text-2xl leading-4 font-medium bg-blue-100 rounded-full">
    <%= link_to 'New Message', new_message_path %>
  </span>
</div>
  <% else %>
  <div class="jumbotron">
    <h1>Unable to create messages. You do not have any active users, who allow SMS.</h1>
  </div>
  <% end %>

</div>

app/views/messages/new.html.erb
<div class="container mt-4">

<h1 class="text-dark mb-2 text-xl">Creating A New Text Message</h1>
	<div class="jumbotron bg-blue-900 text-center shadow">
		<p class="text-white text-lg font-mono">Messages created will be sent to every user who has a registered mobile phone and has opted in to SMS (Text Messages), which is a total of <%= @scope %></p>
	</div>
<%= render 'form', message: @message %>

</div>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>