config/routes.rb
Rails.application.routes.draw do
  resources :inventories
  resources :checkins
  resources :pronouns
  resources :volunteers
  resources :requests
  resources :events
  resources :churches
  resources :carriers
  resources :messages
  resources :users, only: [:index] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
    post :import, on: :collection
  end
  #resources :offerings
  root to: 'pages#home'

  devise_for :users
  match '/alert',:to => 'checkins#alert', :via => :get
  match '/checkin',:to => 'checkins#checkin', :via => :get
  match '/list',:to => 'checkins#list', :via => :get
  match 'nametag/', :to => 'pages#nametag', :via => :get
  match 'nametags/', :to => 'pages#nametags', :via => :get
  match 'all_users/', :to => 'pages#all_users', :via => :get
  match 'get_user/', :to => 'pages#single_user', :via => :get
  match 'offering/', :to => 'pages#offering', :via => :get
  match 'charge/', :to => 'pages#charge', :via => :post
  match 'test/',:to => 'pages#test', :via => :get
  match '/adminify',:to => 'pages#adminify', :via => :get
  match '/financify',:to => 'pages#financify', :via => :get
  match '/card', :to => 'pages#offeringcard', :via => :get
  match '/sucard', :to => 'pages#sucard', :via => :get
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match '/offerings',:to => 'offerings#index', :via => :get
  match '/missing',:to => 'pages#missing', :via => :get
  match '/stopped',:to => 'pages#stopped', :via => :get
  match '/mediareminder', :to => 'pages#MediaReleaseEmail', :via => :get
  match '/checkinEmail',:to => 'pages#checkinEmail', :via => :get
  match '/PrayerChainEmail',:to => 'pages#PrayerChainEmail', :via => :get
  match '/thankyou',:to => 'pages#thankyouEmail', :via => :get
  match '/ackgift',:to => 'offerings#ack', :via => :get
  match '/parishioners',:to => 'pages#parishioners', :via => :get
  match 'edit',:to => 'users#edit', :via => :get
  match 'edit',:to => 'users#update', :via => :put
  match '/mediarelease', :to => 'pages#mediarelease', :via => :get
  
  mount ActionCable.server => '/cable'
  #resources :sessions, only: [:create,:destroy]
  post ':controller(/:action(/:id(.:format)))'
  get ':controller(/:action(/:id(.:format)))'
  


end

app/models/church.rb
class Church < ApplicationRecord
	mount_uploader :avatar, AvatarUploader

	def specialgift
		if self.specialgiftamount?
			return "#{self.specialgiftamount}00"
		else
			return "100"
		end
	end

	def custom_tithing
		if self.giving_override != nil && self.giving_override != ""
			return true
		else
			return false
		end
	end
	def doTwitter(handle)
		return handle.sub("@","https://www.twitter.com/")
	end
	def doInstagram(handle)
		return handle.sub("@","https://www.instagram.com/")
	end
	def doYouTube(handle)
		return handle.sub("@","https://www.youtube.com/")
	end
	def social_links
		spots = 0
		if self.fb?
			spots+= 1
		end
		if self.instagram?
			spots+= 1
		end
		if self.twitter?
			spots+= 1
		end
		if self.yt?
			spots += 1
		end
		response = "<div class='grid grid-cols-#{spots} gap-2 place-items-center mt-2'>"
		if self.fb?
			# Facebook
			response += "<div><a href='#{self.fb}'><img src='https://img.icons8.com/color/50/000000/facebook.png'/></a></div>"
		end
		if self.yt?
			# YouTube
			response += "<div><a href='#{self.yt}'><img src='https://img.icons8.com/color/48/000000/youtube-play.png'/></a></div>"
		end
		if self.instagram?
			# InstaFace
			response += "<div><a href='#{doInstagram(self.instagram)}'><img src='https://img.icons8.com/color/48/000000/instagram-new--v1.png'/></a></div>"
		end
		if self.twitter?
			#twitter
			response += "<div><a href='#{doTwitter(self.twitter)}'><img src='https://img.icons8.com/color/48/000000/twitter--v1.png'/></a></div>"
		end
		response += "</div>"
		return response
	end
	def muted_social
		@links = ""

		if self.twitter?
			@links += '<a href="' + doTwitter(self.twitter) + '" class="me-4 text-reset">
        	<i class="fab fa-twitter"></i></a>'
  		end

  		if self.fb?
			@links += '<a href="' + self.fb + '" class="me-4 text-reset">
        	<i class="fab fa-facebook-f"></i></a>'
  		end

  		if self.yt?
			@links += '<a href="' + self.yt + '" class="me-4 text-reset">
        	<i class="fab fa-youtube"></i></a>'
  		end

  		if self.instagram?
			@links += '<a href="' + doInstagram(self.instagram) + '" class="me-4 text-reset">
        	<i class="fab fa-instagram"></i></a>'
  		end

  		return @links.html_safe()
	end
	def pretty_address_long
    	return "#{self.address} </br> #{self.city}, #{self.state} #{self.zip}".html_safe()
   	end
   	def pretty_address
    	return "#{self.address} #{self.city}, #{self.state}"
   	end
   	def pretty_phone
   		if self.telephone
   			return "(#{self.telephone[0..2]}) #{self.telephone[3..5]}-#{self.telephone[6..9]}"
   		else
   			return "Not Configured Yet"
   		end

   	end
end

app/controllers/churches_controller.rb
class ChurchesController < ApplicationController
  before_action :set_church, only: [:show, :edit, :update, :destroy]

  # GET /churches
  # GET /churches.json
  def index
    @churches = Church.all
  end

  # GET /churches/1
  # GET /churches/1.json
  def show
    @church = Church.first
  end

  # GET /churches/new
  def new
    @church = Church.new
  end

  # GET /churches/1/edit
  def edit
  end

  # POST /churches
  # POST /churches.json
  def create
    @church = Church.new(church_params)

    respond_to do |format|
      if @church.save
        format.html { redirect_to @church, notice: 'Church was successfully created.' }
        format.json { render :show, status: :created, location: @church }
      else
        format.html { render :new }
        format.json { render json: @church.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /churches/1
  # PATCH/PUT /churches/1.json
  def update
    #if params[:shorturl]
      #token = 'o_3r4t3bv8kj:o_3r4t3bv8kj'
      #client = Bitly::API::Client.new(token: token)
      #bitlink = client.shorten(long_url: params[:shorturl])
    #end
    respond_to do |format|
      if @church.update(church_params)
        format.html { redirect_to root_url, notice: 'Church was successfully updated.' }
        format.json { render :show, status: :ok, location: @church }
      else
        format.html { render :edit }
        format.json { render json: @church.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /churches/1
  # DELETE /churches/1.json
  def destroy
    @church.destroy
    respond_to do |format|
      format.html { redirect_to churches_url, notice: 'Church was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_church
      @church = Church.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def church_params
      params.require(:church).permit(:name, :address, :city, :state, :zip, :email, :website, :telephone, :service_time, :pastor, :pastor_email, :fb, :twitter, :instagram, :avatar, :calendly_url, :shorturl, :thankyou, :prayer_chain, :logo,:giving_override,:yt,:specialgiftamount,:specialgifttext,:customgiftenabled)
    end
end

app/helpers/churches_helper.rb
module ChurchesHelper
end

app/views/churches/edit.html.erb
<h1 class="mt-4 mb-4 text-center text-xl bg-gray-200 p-4 rounded shadow">Editing Church</h1>

<%= render 'form', church: @church %>

app/views/churches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Churches</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @churches.each do |church| %>
      <tr>
        <td><%= link_to 'Show', church %></td>
        <td><%= link_to 'Edit', edit_church_path(church) %></td>
        <td><%= link_to 'Destroy', church, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Church', new_church_path %>

app/views/churches/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light indigo">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Dashboard', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Users', '#', class: "nav-link" %>
      </li>
    </ul>
    <span class="navbar-text">
       Create New Church
    </span>
  </div>
</nav>

<%= render 'form', church: @church %>

<%= link_to 'Back', churches_path %>

app/views/churches/show.html.erb
<p id="notice"><%= notice %></p>
<h2>General Info</h2>
<div><%= image_tag(@church.avatar_url) if @church.avatar? %><br></div>
<b>Name:</b>
<%=@church.name%><br>
<b>Address:</b>
<%=@church.address%><br>
<b>City:</b>
<%=@church.city%><br>
<b>State:</b>
<%=@church.state%><br>
<b>Zipcode:</b>
<%=@church.zip%><br>
<%= link_to '<i class="fab fa-facebook-square fa-2x"></i>'.html_safe , @church.fb %>
<%= link_to '<i class="fab fa-twitter-square fa-2x"></i>'.html_safe , @church.twitter %>
<%= link_to '<i class="fab fa-instagram fa-2x"></i>'.html_safe , @church.instagram %>
<hr>
<h2>Pastor Info</h2>
<b>Pastor:</b>
<%=@church.pastor%>(<%=@church.pastor_email%>)
<h2>Service Info</h2>
<%=@church.service_time%><br>


<%= link_to 'Edit', edit_church_path(@church) %> |
<%= link_to 'Back', root_path %>