config/routes.rb
Rails.application.routes.draw do
  resources :inventories
  resources :checkins
  resources :pronouns
  resources :volunteers
  resources :requests
  resources :events
  resources :churches
  resources :carriers
  resources :messages
  resources :users, only: [:index] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
    post :import, on: :collection
  end
  #resources :offerings
  root to: 'pages#home'

  devise_for :users
  match '/alert',:to => 'checkins#alert', :via => :get
  match '/checkin',:to => 'checkins#checkin', :via => :get
  match '/list',:to => 'checkins#list', :via => :get
  match 'nametag/', :to => 'pages#nametag', :via => :get
  match 'nametags/', :to => 'pages#nametags', :via => :get
  match 'all_users/', :to => 'pages#all_users', :via => :get
  match 'get_user/', :to => 'pages#single_user', :via => :get
  match 'offering/', :to => 'pages#offering', :via => :get
  match 'charge/', :to => 'pages#charge', :via => :post
  match 'test/',:to => 'pages#test', :via => :get
  match '/adminify',:to => 'pages#adminify', :via => :get
  match '/financify',:to => 'pages#financify', :via => :get
  match '/card', :to => 'pages#offeringcard', :via => :get
  match '/sucard', :to => 'pages#sucard', :via => :get
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match '/offerings',:to => 'offerings#index', :via => :get
  match '/missing',:to => 'pages#missing', :via => :get
  match '/stopped',:to => 'pages#stopped', :via => :get
  match '/mediareminder', :to => 'pages#MediaReleaseEmail', :via => :get
  match '/checkinEmail',:to => 'pages#checkinEmail', :via => :get
  match '/PrayerChainEmail',:to => 'pages#PrayerChainEmail', :via => :get
  match '/thankyou',:to => 'pages#thankyouEmail', :via => :get
  match '/ackgift',:to => 'offerings#ack', :via => :get
  match '/parishioners',:to => 'pages#parishioners', :via => :get
  match 'edit',:to => 'users#edit', :via => :get
  match 'edit',:to => 'users#update', :via => :put
  match '/mediarelease', :to => 'pages#mediarelease', :via => :get
  
  mount ActionCable.server => '/cable'
  #resources :sessions, only: [:create,:destroy]
  post ':controller(/:action(/:id(.:format)))'
  get ':controller(/:action(/:id(.:format)))'
  


end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :user
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_action :set_checkin, only: [:show, :edit, :update, :destroy]

  # GET /checkins
  # GET /checkins.json
  def index
    @church_count = Church.count
    @church = Church.first
    @checkin_dates = []
    @checkin_hash = {} #date,attendees
      Checkin.all.order(created_at: :desc).each do |c|
        @checkin_dates << c.short_date 
      end
    # GET changed list of unique dates!
    @checkin_dates.uniq!
    @checkins = Checkin.all.order(created_at: :desc)
    @checkedin_users = []
    @checkin_dates.each do |d|
      count = Checkin.all.where('short_date' => d).count
      @checkin_hash.store(d,count)   
    end
    # HOW MANY PPL PER DAY
  end

  # GET /checkins/1
  # GET /checkins/1.json
  def show
  end

  # GET /checkins/new
  def new
    @church = Church.first
    @checkin = Checkin.new
  end

  # GET /checkins/1/edit
  def edit
  end

  def alert
    @day = params[:d]
    
    respond_to do |format|
    if UserMailer.alert(@day).deliver
      format.html do
        redirect_to '/'
      end
    else

    end
  end
  end

  def checkin
    @church = Church.first
    userid = current_user
    if params[:uid]
      userid = User.find(params[:uid])
    end

  #if current_user
    if Checkin.where('short_date' => Time.now.strftime("%m/%d/%Y")).where(:user => userid).count > 0
      # Already Checked in!
      respond_to do |format|
        format.html { redirect_to root_url, notice: 'We already checked you in!' }
        format.text { redirect_to root_url, notice: 'We already checked you in!' }
        format.json { render :show, status: :created, location: @checkin }
      end
    else
      #Check in!
      @checkin = Checkin.new(:user => userid, :short_date => Time.now.strftime("%m/%d/%Y"))
      respond_to do |format|
      if @checkin.save
        format.html { redirect_to root_url, notice: 'Check-In Successful!' }
        format.text { redirect_to root_url, notice: 'Check-In Successful!' }
        format.json { render :show, status: :created, location: @checkin }
      else
        format.html { render :new }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
      end
    end
 end

  # POST /checkins
  # POST /checkins.json
  def create
    @checkin = Checkin.new(checkin_params)

    respond_to do |format|
      if @checkin.save
        format.html { redirect_to @checkin, notice: 'Checkin was successfully created.' }
        format.json { render :show, status: :created, location: @checkin }
      else
        format.html { render :new }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkins/1
  # PATCH/PUT /checkins/1.json
  def update
    respond_to do |format|
      if @checkin.update(checkin_params)
        format.html { redirect_to @checkin, notice: 'Checkin was successfully updated.' }
        format.json { render :show, status: :ok, location: @checkin }
      else
        format.html { render :edit }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkins/1
  # DELETE /checkins/1.json
  def destroy
    @checkin.destroy
    respond_to do |format|
      format.html { redirect_to checkins_url, notice: 'Checkin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def list
     @church_count = Church.count
    @church = Church.first
    @datetoshow = params[:for]
    @checkins = Checkin.all.where('short_date' => @datetoshow)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkin
      @checkin = Checkin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checkin_params
      params.require(:checkin).permit(:user_id,:uid)
    end
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/views/checkins/_form.html.erb
<%= simple_form_for(@checkin) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/checkins/checkin.html.erb
<h1 class="text-red-800 text-xl">Checkin Successful.</h1>

app/views/checkins/edit.html.erb
<h1>Editing Checkin</h1>

<%= render 'form', checkin: @checkin %>

<%= link_to 'Show', @checkin %> |
<%= link_to 'Back', checkins_path %>

app/views/checkins/index.html.erb
<p id="notice"><%= notice %></p>


<% if !@checkin_hash.empty? %> 
  <% @checkin_hash.each do |k,v| %>
    <div class="card m-12">
      <div class="card-header">
        <% if k %>
              In-Person Worship - <%=time_ago_in_words Date.strptime(k, '%m/%d/%Y') %> ago
        <% end %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= link_to k,list_url(for: k) %></h5>
        <p class="card-text">Triggering an alert below will notify attendees to contact the church office telephone number on file.</p>
        <%= link_to "Alert #{v} Attendees", alert_path(:d => k), class: "btn btn-danger text-light opacity-100 text-white" %>
      </div>
    </div>
  <% end %>
<% else %>
  <h1>No  Checkins Yet.</h1>
<% end %>

app/views/checkins/list.html.erb
<h1> Attendees for In Person Worship <span class="text-xl"><%=@datetoshow%></span></h1>

<p class="text-gray-500 m-8 p-4 text-2xl bg-teal-100 rounded-lg">These parishioners were marked as attending worship for the above date. You may contact them individually below or click the alert button from the Checkins Admin Page.</p>


<ul class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
	<% @checkins.each do |c| %>
  <li class="col-span-1 bg-white rounded-lg shadow">
    <div class="w-full flex items-center justify-between p-6 space-x-6">
      <div class="flex-1 truncate">
        <div class="flex items-center space-x-3">
          <h3><%=c.user.fullname%></h3>
          <span class="flex-shrink-0 inline-block px-2 py-0.5 text-teal-800 text-lg leading-4 font-medium bg-teal-100 rounded-full">
          	<% if c.user.admin || c.user.finance %>
          		Admin
          	<% else %>
          		User
          	<% end %>
          		
          	</span>
        </div>
        <p class="mt-1 text-gray-500 text-lg leading-5 truncate">
        <% if c.user.role != "" %>
        	<%= c.user.role %>
        <% else %>
        	Parishioner
        <% end %>
    	</p>
      </div>

      <% if c.user.avatar? %>
    		<%= image_tag c.user.avatar_url , class: 'w-32 h-32 bg-gray-300 rounded-full flex-shrink-0' %>
    	<% else %>
    		<%= image_tag "no_photo.jpg", class: 'w-32 h-32 bg-gray-300 rounded-full flex-shrink-0' %>

    	<% end %>
    </div>
    <div class="border-t border-gray-200">
      <div class="-mt-px flex">
        <div class="w-0 flex-1 flex border-r border-gray-200">
          <a href=mailto:<%= c.user.email %> class="relative -mr-px w-0 flex-1 inline-flex items-center justify-center py-4 text-sm leading-5 text-gray-700 font-medium border border-transparent rounded-bl-lg hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 focus:z-10 transition ease-in-out duration-150">
            <!-- Heroicon name: mail -->
            <svg class="w-5 h-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
              <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
              <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
            </svg>
            <span class="ml-3 text-2xl">Email</span>
          </a>
        </div>
        <div class="-ml-px w-0 flex-1 flex">
          <a href=tel:<%= c.user.telephone %> class="relative w-0 flex-1 inline-flex items-center justify-center py-4 text-sm leading-5 text-gray-700 font-medium border border-transparent rounded-br-lg hover:text-gray-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 focus:z-10 transition ease-in-out duration-150">
            <!-- Heroicon name: phone -->
            <svg class="w-5 h-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
              <path d="M2 3a1 1 0 011-1h2.153a1 1 0 01.986.836l.74 4.435a1 1 0 01-.54 1.06l-1.548.773a11.037 11.037 0 006.105 6.105l.774-1.548a1 1 0 011.059-.54l4.435.74a1 1 0 01.836.986V17a1 1 0 01-1 1h-2C7.82 18 2 12.18 2 5V3z" />
            </svg>
            <span class="ml-3 text-2xl">Call</span>
          </a>
        </div>
      </div>
    </div>
  </li>
	<% end %>
</ul>

app/views/checkins/new.html.erb
<h1>New Checkin</h1>

<%= render 'form', checkin: @checkin %>

<%= link_to 'Back', checkins_path %>

app/views/checkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @checkin.user %>
</p>

<%= link_to 'Edit', edit_checkin_path(@checkin) %> |
<%= link_to 'Back', checkins_path %>